---
- name: CentOS | Remove Old Docker Versions
  yum:
    name: "{{ item }}"
    state: "absent"
  with_items:
    - "docker"
    - "docker-client"
    - "docker-client-latest"
    - "docker-common"
    - "docker-latest"
    - "docker-latest-logrotate"
    - "docker-logrotate"
    - "docker-selinux"
    - "docker-engine-selinux"
    - "docker-engine"

- name: CentOS | Add Docker Repository
  yum_repository:
    name: docker-ce
    description: Docker-CE
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable/

- rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: CentOS | Install DockerCE
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "device-mapper-persistent-data"
    - "lvm2"
    - "docker-ce"

- name: CentOS | Start the Docker Service
  service: name=docker state=started enabled=yes
...