---
- name: Debian/Ubuntu | Remove Old Docker versions
  apt:
    state: "absent"
    name:
      - "docker"
      - "docker-engine"
      - "docker.io"

- name: Debian/Ubuntu | Install Docker Dependencies
  apt:
    update_cache: "yes"
    state: "present"
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "software-properties-common"
      - "curl"
      - "python-docker"

- name: Debian | Debian Specific Dependencies
  apt:
    update_cache: "yes"
    name: "gnupg2"
    state: "present"
  when: ansible_distribution|lower == 'debian'

- name: Debian/Ubuntu | Get the Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: "present"

- name: Debian/Ubuntu | Add the Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable
    state: "present"

- name: Debian/Ubuntu | Install DockerCE
  apt: 
    update_cache: "yes"
    name: "docker-ce"
    state: "latest"
    
- name: Debian/Ubuntu | Start the Docker Service
  service: name=docker state=started enabled=yes
...